### ISSUE TITLE
csvToJson method updates

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#125]
**Is your feature request related to a problem? Please describe.**
Ok, so we have a few problems with csvToJson method.
- [ ] First was mentioned
https://user-images.githubusercontent.com/25102007/63653054-47c03c00-c781-11e9-9a0d-5af716b5cf37.png

- [ ] I add a lot of comments inside at those 3 methods, so we solve them as well.

**Describe the solution you'd like**
Our updated version should be able to handle both 3 datasets. We updating those parsers from different directions, it maybe not productive, but soon or later we'll be able to handle that.

**Comment by atherdon** [comment]
tell me what part do you want to take, please

**Comment by atherdon** [comment]
i'll back in a few hours and make a new release of our module, as i moved out FAO parser

**Comment by SyeedHasan** [comment]
Here's my solution:

1. `csvToJson` function receives a directory variable which has the DIRECTORY name (for example USFA/Nutrition...). Simply cut it out using regex and you get USFA.

2. Pass it down to the function `fileWriter` by means of `splitJsonIntoFiles` where we can remove USFA. Change it with the template string carrying our new variable.

3. Now, if the dataset changes, we won't need to manually insert it inside. 
It'll be
`/projects/{parentDirName}/${folderName}/${fileName}${i}.json` 
`/projects/USFA/${folderName}/${fileName}${i}.json`
`/projects/FAO/${folderName}/${fileName}${i}.json`
`/projects/FoodComposition/${folderName}/${fileName}${i}.json`

**Comment by SyeedHasan** [comment]
Is this approach good?

**Comment by atherdon** [comment]
first of all - we should think aboout code inside of `src` folder as independent module from our actual 'datasets' and 'parsers'.
So we need to make it work without an actuall connection to any of datasets, i.e. in our next result we shouldn't have any things like `usfa` inside.

let's split it into a small chunks.
our first target here is 'fileWriter' method. it's first place that can/should be improved

**Comment by atherdon** [comment]
> Here's my solution:
> 1. `csvToJson` function receives a directory variable which has the DIRECTORY name (for example USFA/Nutrition...). Simply cut it out using regex and you get USFA.

I don't think it necessary. i mean right now we working on 2 datasets/parser scripts at the same time. We can easily adjust them, depending to changes, that we'll make at our
But maybe i'm not understanding your solution correctly. Back to it later and remind me, because your idea may be good.

> 2. Pass it down to the function `fileWriter` by means of `splitJsonIntoFiles` where we can remove USFA. Change it with the template string carrying our new variable.
> 3. Now, if the dataset changes, we won't need to manually insert it inside.
>    It'll be
>    `/projects/{parentDirName}/${folderName}/${fileName}${i}.json`
>    `/projects/USFA/${folderName}/${fileName}${i}.json`
>    `/projects/FAO/${folderName}/${fileName}${i}.json`
>    `/projects/FoodComposition/${folderName}/${fileName}${i}.json`

The major issue, why we need to make it more simple and also less confusing for our side - because we shouldn't care about logic of actual parser script here. I mean that our main goal is to have methods that can be used, right? When you open 3 different folders with datasets - you'll see that each of it have different folder structure inside with csv files. so if we'll try just to make a solution that will make happy all 3 cases - it will just make code harder. it's my take.
you see that with all of our changes we only making it less complex/less long/ less confusing. this is what it make this approach a good way to create a software

**Comment by atherdon** [comment]
btw, just made a new release at npm

**Comment by atherdon** [comment]
at `fileWriter` we have a few tasks that we should address:
https://github.com/GroceriStar/food-datasets-csv-parser/blob/master/src/csvToJson.js#L20-L37
1) rename the method
2) ` const jsonFileName = `${folderName}/${fileName}${i}.json`;` I don't see here an actual folder name. i think it's a mistake
3) `const jsonPath = `/projects/USFA/${jsonFileName}`;` this line is no longer acceptabale and also wouldn't work well. Because now we move out all of our datasets from the inside of `src` folder into an outside folder (projects2.0 for now)

**Comment by SyeedHasan** [comment]
> 3. `const jsonPath = `/projects/USFA/${jsonFileName}`;` this line is no longer acceptabale and also wouldn't work well. Because now we move out all of our datasets from the inside of `src` folder into an outside folder (projects2.0 for now)

Where should the JSON files go? Project2.0 directory?

**Comment by atherdon** [comment]
we should pass a proper path from the outside.

>

**Comment by atherdon** [comment]
@zhangted what do you think about this task?

**Comment by atherdon** [comment]
I understand and agree with your logic. it's correct.
my take on it. i came at JS from PHP - and we have there so long and boring
names.
as both `split.../assign...` and `generate...` methods are internal and
used/called only one time - i think we can easily rename it into
a) `assign`
b) `generate`
c) add/update information at readme, about those methods so everyone else
will be on the same page with us

sort names are short and look better, right?

>

**Comment by zhangted** [comment]
yeah. for sure. i updated. also i saw the new comment about too many data entires for the generate function. maybe it is possible to slice the data before passing into generate, then we can eliminate 3 variables from that function

**Comment by atherdon** [comment]
we'll address that in a new PR.
as I add it as TODO - we wouldn't miss it

>

**Comment by atherdon** [comment]
#136

**Comment by SyeedHasan** [comment]
Hi Arthur, the PR is merged now I guess. Should we move the main function to index.js as stated?

**Comment by atherdon** [comment]
@SyeedHasan do you mean csvToJson method, right?
Yes i think we can do this. it should be done carefully, because it can break some of our parsers.
please do, open a PR and i'll take a look.

**Comment by EbrahimKreem** [comment]
There is a well-known library with a great API that can do the work for` csvToJson`  method so I think there is no need to reinvent the wheel... https://www.npmjs.com/package/csvtojson

**Comment by atherdon** [comment]
@EbrahimKreem I saw it while ago. but for now, i think we need to keep moving by my plan.
when we'll limit differences between parser files, and parsing will work correctly, we'll have free time and be able to check other methods. but at this moment I assume we need to move forward current codebase.
I think you were checking parsers before - do you have questions what we need to do or what should be improved?

**Comment by EbrahimKreem** [comment]
yes I am checking parsers but there are a lot of problems related to `csvToJson` method

**Comment by EbrahimKreem** [comment]
so how should we fix parsers when our methods have a lot of problems !!!

**Comment by atherdon** [comment]
give me more details about issues that you spotted at `csvToJson` methods.
if we need to fix csvToJson - then we should do it. because before our code
was working at previous repository. I think you was part of that code - so
it will be easy to fix I think

>

**Comment by EbrahimKreem** [comment]
when I try to run the file any parser in projects2.0 I get

![Screenshot from 2019-09-22 13-46-56](https://user-images.githubusercontent.com/32773511/65386066-7b21c680-dd3f-11e9-8b4e-820a65c9201d.png)

**Comment by EbrahimKreem** [comment]
I inspect the code and the error is in csvToJson 
https://github.com/GroceriStar/food-datasets-csv-parser/blob/961eded086dcd1540e6dc2d1e2c7bb0b21470611/src/csvToJson.js#L87

**Comment by atherdon** [comment]
the problem with code, located at projects2.0 is - that code were working
when everything was part of sd folder, then, when we decide to split code
between modules, some parts can be broken, but that changes will be mirror,
by my opinion.

>

**Comment by atherdon** [comment]
> I inspect the code and the error is in `csvToJson` method
> https://github.com/GroceriStar/food-datasets-csv-parser/blob/961eded086dcd1540e6dc2d1e2c7bb0b21470611/src/csvToJson.js#L87
> 

This issue is pretty simple. if you compare logic of folders inside of foodcomposition or usfa - you'll see differences between them.
try to run parser from another project - one of them should go through that line. it might help you to figure out. 

---

> it can not read '0' of undefined because we are not providing any arguments in `getHeaders` function
> https://github.com/GroceriStar/food-datasets-csv-parser/blob/961eded086dcd1540e6dc2d1e2c7bb0b21470611/src/getHeaders.js#L6
> 
> and the code in `csvToJson.js` file is very complicated 🤕


You can make it simple :) I think your experience is more than enough to do it. you just need to spend more time at debuggin it. again, use me - make some changes, open pull request and lets figure it out together

**Comment by atherdon** [comment]
@EbrahimKreem I plan to create a simple video that will explain more about changes we're making. tell me if you need that kind of explanation and feel free to ask more questions

Also, about line, that contains a path to an actual, `raw` CSV files inside at `csvToJson` - I think we should pass that kind of path to this method from the outside because we're making our method more independent from our datasets.

**Comment by EbrahimKreem** [comment]
what do we expect from `csvToJson` method to do alongside parsing?

**Comment by atherdon** [comment]
> what do we expect from `csvToJson` method to do alongside parsing?

for our current stage, I want to have this module to be independently working with 3 datasets that we have inside of this repo at this moment.
But if we'll decide to parse another dataset - it shouldn't be an issue as well. this is the major goal.
So if you want to make changes at csvToJson - feel free to do it. if something goes wrong - we can easily revert if - if needed.

**Comment by atherdon** [comment]
you can also check how projects3.0 looks like - it may give you some more ideas about how i see it.

**Comment by EbrahimKreem** [comment]
Hi @atherdon, now we get some data returned from `getHeaders` function 
![Screenshot from 2019-09-26 10-05-38](https://user-images.githubusercontent.com/32773511/65665922-46ff1c00-e045-11e9-8740-cca288049e97.png)
so now we should fix logic inside `csvToJson` and `parseDirectoryFiles` to parse CSV files to json... am I correct?

**Comment by EbrahimKreem** [comment]
so now we should fix logic inside `csvToJson` and `parseDirectoryFiles` to parse CSV files to json... am I correct?

**Comment by atherdon** [comment]
Looks correct for me by quick look. as i'm concerned about `getHeaders`
method, can you test it with other datasets as well?

and please open pull request, even if you have "work-in-progress"

>

**Comment by zhangted** [comment]
Hey guys, playing catch up. @EbrahimKreem I edited the methods in csvToJson to reduce the amount of variables being passed aroun, as per the TODOs, but maybe it needs simplification. I also updated the readme to explain any changes I made.  

I think the methods in csvToJson work, except for the file naming/directory part in the `generate` function. The jsonPath is /projects/${jsonFileName}, but I don't think a folder named  `projects` exists in the directory.

**Comment by atherdon** [comment]
@zhangted did you open a pull request with your changes? please do because
we cannot see it in our main repository

>

**Comment by atherdon** [comment]
> I think the methods in csvToJson work, except for the file naming/directory part in the `generate` function. The jsonPath is /projects/${jsonFileName}, but I don't think a folder named `projects` exists in the directory.

Ted, can you handle that and submit a new PR?

**Comment by zhangted** [comment]
> > I think the methods in csvToJson work, except for the file naming/directory part in the `generate` function. The jsonPath is /projects/${jsonFileName}, but I don't think a folder named `projects` exists in the directory.
> 
> Ted, can you handle that and submit a new PR?

I will try. Where is static-data-generator or the write function in the line 
`import { write } from '@groceristar/static-data-generator';` ?
I also want to check this function

**Comment by EbrahimKreem** [comment]
> Where is static-data-generator or the write function in the line
import { write } from '@groceristar/static-data-generator'; ? Is it suppose to be food-static-files-generator?

https://github.com/GroceriStar/food-static-files-generator/blob/d09a7031f425bb191344e09527afcaee8579f7a9/src/fileSystem.js#L24

**Comment by atherdon** [comment]
> So should I update the projects part of jsonPath to projects2.0 or 3.0?

@zhangted  as we want later to have this module working from the outside, i think we should have some sort of attribute, instead of the hardcoded path as we have now.
'@groceristar/static-data-generator' is the name of module, published on npm. 
`food-static-files-generator` is the repository name on github where we saving our code, related to `generator module`

**Comment by zhangted** [comment]
Ok I got the json file writing to actually write, but when i check the file, theres a bunch of undefineds and empty quotes? Sending PR now

**Comment by atherdon** [comment]
@zhangted what command do you using for start parser?

**Comment by zhangted** [comment]
> @zhangted what command do you using for start parser?

I go to the directory with a parser.js and run "node parser.js"

**Comment by atherdon** [comment]
@zhangted can you add that line to package.json so we can re-use it?

**Comment by zhangted** [comment]
there are a couple of lines (csv:fc, csv:usfa1...etc) in there that do it. As long as the directory has csv files in it, it works (like csv:fao1 command). Some of them without csv files returns some weird error when runing it. i added an example working command `  "csv:fish_reftbl": "node ./projects2.0/FAO/Fish/Fish_Reftbl_RefDatasets/parser",`

**Comment by atherdon** [comment]
@zhangted sure, I add those links to make it less confusing.
I plan to add some script that will run all parsers at the same time later :)

**Comment by zhangted** [comment]
@EbrahimKreem @atherdon Is the format in the json file about right?(https://i.imgur.com/7W1mrQ5.png)  I will push changes on top of EbrahimKreem's pull request.

**Comment by atherdon** [comment]
> @EbrahimKreem @atherdon Is the format in the json file about right?(https://i.imgur.com/7W1mrQ5.png) I will push changes on top of EbrahimKreem's pull request.

It's hard to tell, because it's not formatted and we cannot compare and catch some quick issues.
At sd repository we have some sort of validator, but again - this datasets is huge, so it's not clear now. maybe you can go with loop and print some parts of these huge objects and it can help us to compare data inside of rows.

i tend to think that it's ok, because we using code that was created before and we improving it again and again, but if the mistake can appear - it will appear.

another way to confirm it - try to use the similar code for other datasets and if it will work correctly too - then changes go higher.

not sure if it will work actually with my latest changes - but it definitely better than before

**Comment by atherdon** [comment]
@Abobos  here is another long conversation about our ongoing work. please take a look, check codebase and tell me your questions (also we trying to put a lot of information into Readme file)

**Comment by atherdon** [comment]
@EbrahimKreem should we close this task by your opinion

**Comment by EbrahimKreem** [comment]
the discussion here is outdated with our latest changes so in my opinion the issue should be closed
