### ISSUE TITLE
[blocker] package.json script bug

### ISSUE THREAD

**Issue by EbrahimKreem** [GroceriStar/food-datasets-csv-parser#170]
**Describe the bug**
when I run the parser from the package.json script I get `Error: ENOENT: no such file or directory, open 'Fish_Reftbl_RefDatasets.csv'`

when I enter the dir and run `node parser.js` everything works correctly

**Expected behavior**
it should run the parser from the package.json script successfully

**Comment by atherdon** [comment]
@zhangted I think it related to your changes

**Comment by zhangted** [comment]
What is the difference between running `node ./projects2.0/FAO/Fish/Fish_NV_Sum/parser` or going into the folder and running `node parser`?

**Comment by atherdon** [comment]
it depends and debatable.
from nodejs stand point - it might be similar
from code quality - it mean something
from long distance, team collaboration, bugs - it means something too

just follow my lean and fix this issue

>

**Comment by zhangted** [comment]
Okay,  if we know difference, then we can fix why it works one way and not the other

**Comment by EbrahimKreem** [comment]
it's a very confusing issue I tried to copy the csv file to the root dir and run the script again and I get the same result

**Comment by atherdon** [comment]
i have some hits for you.
we need to look for issues at `parseDirectoryFiles` - because right now it's our main method that we call at our parsers.

I will add `console.logs` inside of this method, but someone will need to remove them when we finish... Then you both will need to sync your forks and run local builds in order to get latest stuff

you see, this is an actually great example of how separation, the modular structure is a great way to catch problems.

Imagine if we also have good test coverage for this module and it can be automatically found, not by your hands....

**Comment by EbrahimKreem** [comment]
yeah, I totally agree with you ...
but I have a small change I don't know if it's useful or no we can use the `__dirname` var before any CSV file `await parseCsv(`${__dirname}/Fish_Reftbl_RefDatasets.csv`);` and I tested the package.json script and it works fine

**Comment by atherdon** [comment]
I pushed the latest changes to master branch please take a look...

---

@EbrahimKreem I like that improvement. let's have it. but it will work only for projects2.0/FAO case

i like it - let's use it.

**Comment by EbrahimKreem** [comment]
there is a small issue related to `parseDirectoryFiles`  we are passing an array to `csvToJson` method and it expects to receive a path and I get `TypeError: path must be a string or Buffer`
https://github.com/GroceriStar/food-datasets-csv-parser/blob/bd0daef99246068802ea29c583a018b6790ad012/src/fileSystem.js#L28

**Comment by zhangted** [comment]
> there is a small issue related to `parseDirectoryFiles` we are passing an array to `csvToJson` method and it expects to receive a path and I get `TypeError: path must be a string or Buffer`
> #172
> https://github.com/GroceriStar/food-datasets-csv-parser/blob/bd0daef99246068802ea29c583a018b6790ad012/src/fileSystem.js#L28

@EbrahimKreem Maybe concat the file info into a string for the path?
 `''.concat(fileInfo[0], __dirname, fileInfo[1], '.csv') `

Also, should we be calling the `assign` function in the `resolve(dataEntries)` part in the createReadStream? Otherwise we are not making the files

Also, why are there 3 parameters for csvToJson? I thought we are only passing 2 parameters into it. It may seem complicated to keep the path separated but the reason why I think we should keep it that way is because we have to add numbers to the end of the file name for every file

**Comment by atherdon** [comment]
now I actually can saw this issue on my side as well.
what i'm doing with it - you will ask me?
i typing this error to google. now sure why you can't do it as well :( 

I add a few `console.logs` that should help to debug 
![image](https://user-images.githubusercontent.com/1469198/66086843-16a40a00-e57e-11e9-867f-48fba17e33c1.png)

**Comment by zhangted** [comment]
this is what I get when I run the csv:fao1 and csv:fish_reftbl commands

**Comment by EbrahimKreem** [comment]
> when I run the parser from the package.json script I get
Error: ENOENT: no such file or directory, open 'Fish_Reftbl_RefDatasets.csv'

the issue now is in`mainWrapper` fn when we use `__dirname` it resolves to `/food-datasets-csv-parser/src` but when the `__dirname` was in the parser it resolves to `/food-datasets-csv-parser/projects2.0/FAO/Fish/Fish_Reftbl_RefDatasets/parser.js`

**Comment by EbrahimKreem** [comment]
my bad the I pressed the `close and comment` button wrongly :sweat_smile:

**Comment by EbrahimKreem** [comment]
> when I run the parser from the package.json script I get
Error: ENOENT: no such file or directory, open 'Fish_Reftbl_RefDatasets.csv'

the issue is in the context of `__dirname` in `mainWrapper` fn the `__dirname` resolves to `/food-datasets-csv-parser/src` 
 we should use the `__dirname` in the parser file and everything will work correctly

**Comment by EbrahimKreem** [comment]
#189

![Screenshot from 2019-10-03 09-02-06](https://user-images.githubusercontent.com/32773511/66102961-ca2bef00-e5bc-11e9-94a2-291e05528104.png)

**Comment by atherdon** [comment]
i tried to debug this thing as well, but i was falling asleep and become
lazy.
try to solve it on your own

>

**Comment by atherdon** [comment]
@EbrahimKreem @zhangted can you tell me some updates? 
i think we spot some issues with parsers, and I comment some code in order to have more clear idea what is not working?
are anyone else working on this thing? i'll be happy to get your help - as usually busy with other tasks

**Comment by EbrahimKreem** [comment]
1- we should figure out how to parse the CSV file to JSON and save it to the file system in `FAO/Fish`
1- update other parsers

**Comment by atherdon** [comment]
i think it's easy - most work was dobe before and we just cleaning it up.
let's fix issues that we have at parseDirectoryFiles - and this generation of parsers probably will work.
then we'll made some upgrades in order to move code into `projects3.0` state

**Comment by EbrahimKreem** [comment]
I have some work that needs a discussion I will make a PR and we can talk there

**Comment by atherdon** [comment]
@EbrahimKreem I think we finished it and i can close an issue, right?
