### ISSUE TITLE
csvToJson improvement

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#174]
**Is your feature request related to a problem? Please describe.**
1. Disable eslint-disable - remove first line at file
2. run `yarn lint`
3. fix issues
4. push them as PR

**Is it was created as task at GitHub issues? Please provide an issue number or link**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by atherdon** [comment]
@sibasish14 check this one. tell me if it's not clear

**Comment by sibasish14** [comment]
`remove the first line at file`- which file are you referring to? I don't think it's `csvToJson.js`

**Comment by atherdon** [comment]
in order to speed up our development I disabled ESLint warnings for a few
files that we have inside of our src folder.
I think i'm talking about csvToJson.js - does it have comment at it's first
line?

>

**Comment by sibasish14** [comment]
No, `csvToJson.js` doesn't have any comment line in the first line.

**Comment by atherdon** [comment]
Ok, i think it's solved now. Can you confirm that eslint doesn't generate warnings?

**Comment by atherdon** [comment]
if eslint is generating warnings - please fix few of them and submit PR
