### ISSUE TITLE
if now we don't use getHeaders in a straight way - maybe it better to remove it's export at index.js?

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#180]
if now we don't use getHeaders in a streight way - maybe it better to remove it's export at index.js?

_Originally posted by @atherdon in https://github.com/GroceriStar/food-datasets-csv-parser/pull/175/files_

**Comment by atherdon** [comment]
right now it's useful because i add quick shit turnaround with new wrapper method at index.js
but it's a bad way to do...

**Comment by atherdon** [comment]
@sibasish14 you can grab this task

**Comment by atherdon** [comment]
feel free to ask more details - i create this task quickly - just to not lose details

**Comment by sibasish14** [comment]
This is what I understand after going through `index.js` (and the other files in the `src` folder): I need to remove (or comment out?) the line 48, i.e., `getHeaders,`. Am I correct? Please guide me if I am wrong.

**Comment by atherdon** [comment]
yes you can remove importing/exporting line.
But when you do it - it can break method below that i shitcoded :)
So you'll need to move that method away to another file, and make it work.

>

**Comment by sibasish14** [comment]
Do you mean the `mainWrapper` method?

Ok, so, this is my interpretation after going through some more files: many `parser.js` files are importing `index.js`. And hence, the `mainWrapper` method won't work if we remove the import/export lines.

Am I correct? If yes, then I should be doing the following:
1. create a new file `mainWrapper.js` and remove it from index.js
2. remove the import/export of `getHeaders`

Right?

If no, what should I do then?

**Comment by atherdon** [comment]
fork a code and make this changes - then open a pull request.
I think you correct - but without seeing a code - it's hard to tell for me

>

**Comment by sibasish14** [comment]
@atherdon I have opened a PR for this issue. Please tell me if I have to change anything.

**Comment by atherdon** [comment]
i think it was done, right? can I close this issue?

**Comment by sibasish14** [comment]
Yes
