### ISSUE TITLE
test getHeaders with 3 datasets

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#188]
Hi @atherdon, now we get some data returned from `getHeaders` function 

![Screenshot from 2019-09-26 10-05-38](https://user-images.githubusercontent.com/32773511/65665922-46ff1c00-e045-11e9-8740-cca288049e97.png)

_Originally posted by @EbrahimKreem in https://github.com/GroceriStar/food-datasets-csv-parser/issues/125#issuecomment-535372067_

**Comment by EbrahimKreem** [comment]
why we have a lot of datasets? does two or three datasets do the testing thing?

**Comment by atherdon** [comment]
the main reason is to make our codebase work.
second options is to help other food projects that have similar way to ours.
i.e. when we'll make it work great - i plan to release this module online and share with everyone who building food tech projects

**Comment by atherdon** [comment]
when parser will work as it should in my mind - we'll focus on re-creating our backend system using graphql.
and my goal is try to create it with modularity in mind as well.
imagine situation that we have a backend system that can handle different datasets and be able to work for different cases - that we trying to cover - i think it will be cool.

prev API that I developed - was created pretty quickly, and it works OK. but when I decide to extend it - it goes so slow, so i decide to leave that system behind.
graphql is a less mature framework, but I see it promise, especially for startups like we building, because it should be more flexible, while we searching for our 'place'

**Comment by atherdon** [comment]
I actually think that getHeaders works fine.
I checked most of datasets - and all was ok. some files have a lot of headers, but I still think that this part wouldn't be an issue for us
