### ISSUE TITLE
Can we replace this method with `read` method from generator?

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#193]
Can we replace this method with `read` method from generator?

_Originally posted by @atherdon in https://github.com/GroceriStar/food-datasets-csv-parser/pull/191_

@EbrahimKreem

**Comment by atherdon** [comment]
I think fs.read is doing the same thing, so it's not necessary to create it from scratch again - because it's making this module more complex  - later we'll clean up code/dependencies

**Comment by EbrahimKreem** [comment]
> I think fs.read is doing the same thing, so it's not necessary to create it from scratch again - because it's making this module more complex - later we'll clean up code/dependencies

which method?

**Comment by atherdon** [comment]
https://github.com/GroceriStar/food-datasets-csv-parser/blob/master/src/csvToJson.js#L59-L66

**Comment by EbrahimKreem** [comment]
I read the code in `read` fn it is reading files, not directories but in `csvToJson` we are reading the directory to extract the name of CSV file and assign it to `write` method

**Comment by atherdon** [comment]
ok, if you think so - then let's move that part of code into `generator` and call it inside of `csv-parser`

**Comment by EbrahimKreem** [comment]
I think this issue can be closed with the latest changes
