### ISSUE TITLE
i think csvToJson should be improved a bit.

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#194]
i think csvToJson should be improved a bit. 
one of our goal is to have inside of csvtojson 2 options:
1) you parsing whole CSV file into one json file
2) you parsing CSV file into a set of json files, that splitted in chunks.

for second case I think we should use assign, that has `write` inside of it

Btw, can you update other parsers accordingly and test how they works with changes that youve made?

_Originally posted by @atherdon in https://github.com/GroceriStar/food-datasets-csv-parser/pull/191#issuecomment-538945865_

**Comment by EbrahimKreem** [comment]
> for second case I think we should use assign, that has write inside of it

the problem is how to know that the consumer of the function want to parse it to one JSON file or split it in chunks

**Comment by atherdon** [comment]
right now we our customer.
and we need to have +1 attribute that we can pass or don't pass.
if we passed that attribute - then we want to split it into chunks - easy
peasy :)

>

**Comment by EbrahimKreem** [comment]
we have a small problem related to `@groceristar/static-data-generator` when I try to run the script I get 

![Screenshot from 2019-10-13 20-43-11](https://user-images.githubusercontent.com/32773511/66719553-1e737200-edfa-11e9-85b9-7000f0f67fa2.png)

**Comment by EbrahimKreem** [comment]
#298

**Comment by EbrahimKreem** [comment]
I made a PR that fixes the issue please make a new release for the module

**Comment by atherdon** [comment]
got it

**Comment by atherdon** [comment]
@EbrahimKreem I push changes to npm

**Comment by EbrahimKreem** [comment]
as I move through the code of `assign` it will generate a file for each (row, object) is this the behavior we want

**Comment by atherdon** [comment]
it depends on case.
I assume that the main goal for split is this case:
we have a dataset with 17k of rows. and for tests - we don't need all this
data to be loaded.
So we decide to split dataset to 17 files with 1000 objects in each file.
Does that make sense?
tell me if it still not clear

>

**Comment by EbrahimKreem** [comment]
Do you mean that it should make a file for every 1000 objects

**Comment by EbrahimKreem** [comment]
yeah it makes sense now

**Comment by atherdon** [comment]
Ok, so should we move our methods away from fileSystem or just remove it
totally?

>

**Comment by atherdon** [comment]
if all duplicates from projects2.0 is removed - let's move functionality
into projects3.0 - i think it will improve our process and also we'll be
able to tweak our code a bit

>

**Comment by EbrahimKreem** [comment]
1- `filesystem.js` purpose was to read directory files and now we use `readDir` method from generator and it should be removed totally
2- `utils.js` there are some duplicates with generator and I think we should remove them

**Comment by atherdon** [comment]
I'm ok with your proposes - let's go :)

**Comment by atherdon** [comment]
I think we didn't finish this task.
because at these lines we running it twice: https://github.com/GroceriStar/food-datasets-csv-parser/blob/master/src/mainWrapper.js#L34-L37

**Comment by atherdon** [comment]
now it's completed and can be closed, right?

**Comment by EbrahimKreem** [comment]
yes

**Comment by atherdon** [comment]
Perfecto!
