### ISSUE TITLE
we have a build error here, but I tend to merge this PR

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#204]
we have a build error here, but I tend to merge this PR

build output: https://travis-ci.org/GroceriStar/food-datasets-csv-parser/jobs/597514887

_Originally posted by @atherdon in https://github.com/GroceriStar/food-datasets-csv-parser/pull/202#issuecomment-541873179_

**Comment by atherdon** [comment]
@sibasish14 can you update it?

**Comment by sibasish14** [comment]
I'm new to testing. But I'll try.
I went through the logs and it says `The command "npm run lint" failed and exited with 1 during.` So I think the code written, doesn't match the ESLint rules. Should I update the `mainWrapper.js` file as per the ESLint rules?

**Comment by EbrahimKreem** [comment]
you should use default export and this will solve the problem https://github.com/GroceriStar/food-datasets-csv-parser/blob/6671b22a6d44d51f2f0dff1d4ede15fc07ec64b3/src/mainWrapper.js#L37

**Comment by EbrahimKreem** [comment]
but I have one question how did `lint-staged` let you make a commit?

our config runs `lint-staged` in staged files before any commit to check eslint rules if there is an error it will not let you commit until you fix the error.

when you try to commit do these lines appear in your terminal or no?

![Screenshot from 2019-10-15 14-15-27](https://user-images.githubusercontent.com/32773511/66826914-47a91500-ef56-11e9-9bdd-05bec73200d2.png)

**Comment by sibasish14** [comment]
> you should use default export and this will solve the problem

So I should basically add a default: `export default {`

> but I have one question how did lint-staged let you make a commit?
our config runs linter in staged files before any commit to check eslint rules if there is an error it will not let you commit until you fix the error.
when you try to commit do these lines appear in your terminal or no?

I didn't notice any tests being run while I was committing. I will check this time I commit and tell you.

**Comment by EbrahimKreem** [comment]
> I didn't notice any tests being run while I was committing. I will check this time I commit and tell you.

what type of os your running on your computer?

**Comment by sibasish14** [comment]
Ubuntu 18.04

**Comment by EbrahimKreem** [comment]
did you install `node-modules` of the repo or no

**Comment by sibasish14** [comment]
No. I didn't know I had to install it. 
How do I do it? Using: `npm install @groceristar/food-datasets-csv-parser`?

**Comment by EbrahimKreem** [comment]
`npm install`

**Comment by sibasish14** [comment]
Where do I run it? In the directory of my clone?

**Comment by EbrahimKreem** [comment]
yes

**Comment by sibasish14** [comment]
![Screenshot from 2019-10-15 22-24-58](https://user-images.githubusercontent.com/33897888/66852480-b019e580-ef9a-11e9-9b84-f78e42f70eaf.png)
I am getting this error.

**Comment by EbrahimKreem** [comment]
run the command with `sudo`

**Comment by EbrahimKreem** [comment]
`sudo npm install`

**Comment by sibasish14** [comment]
![Screenshot from 2019-10-15 22-31-40](https://user-images.githubusercontent.com/33897888/66852874-97f69600-ef9b-11e9-87e1-20740778b0aa.png)
Is it done now?

**Comment by sibasish14** [comment]
> what type of theme you have in your terminal I am curious about it?

Oh My Zsh...it has various themes.

**Comment by EbrahimKreem** [comment]
> Is it done now?

yes

**Comment by sibasish14** [comment]
One last doubt... Do I need to always run `npm install` whenever I update my repo?

**Comment by EbrahimKreem** [comment]
no, you don't need to do it

**Comment by EbrahimKreem** [comment]
to learn more about npm read this article https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/

**Comment by atherdon** [comment]
i'll advice to re-run n[m install each time when you sync your fork with
master branch, because we updating packages frequently so i'm always
updating something :)

>

**Comment by sibasish14** [comment]
I have fixed this https://github.com/GroceriStar/food-datasets-csv-parser/pull/206
