### ISSUE TITLE
refactor parsers to use `mainWrapper` 

### ISSUE THREAD

**Issue by EbrahimKreem** [GroceriStar/food-datasets-csv-parser#208]
**Is your feature request related to a problem? Please describe.**
with @sibasish14 latest changes in `mainWrapper` I think we should refactor all parsers to use it to reduce code duplication 

**Describe the solution you'd like**
refactor all parsers to use `mainWrapper` fn in projects2.0

**Comment by EbrahimKreem** [comment]
#207

**Comment by atherdon** [comment]
@EbrahimKreem was it completed or @sibasish14 can take a look and make some improvements?

**Comment by EbrahimKreem** [comment]
yeah @sibasish14 can take a look at it my focus now is on code documenting and updating the readme

**Comment by EbrahimKreem** [comment]
do you suggest that I should go to projects3.0 first?

**Comment by atherdon** [comment]
I don't know - what is best for you.
I plan to shoot a video and explain our next moves - but I with other stuff
- so do what is better and i'll try to solve my tasks and get back.

I plan to get back one of our experienced interns - he stuck with current
university course - but it hurts to his coding learning curve.

Btw, if you want to start with projects3.0 - i'll need to publish a new
version of our module, so you'll be able to upgrade it and use a recent
version.
Tell me if I need to publish it ASAP

>

**Comment by EbrahimKreem** [comment]
what was projects3.0 purpose? I forgot :smile:

**Comment by atherdon** [comment]
lol.
Main purpose is go away from old and stupid es5 version ~~ projects2.0
because we keeping all projects in one folder just for now, so our team
members was less confused.
I think one of our goals is to create a microservice with csv parser that
will run on heroku so anyone can parse their stuff when he wants.
And clean up and code upgrade will really help and our project will go to a
next evolutionary step

>

**Comment by atherdon** [comment]
you'll easily get used to it. I tried to reduce every problem that we have
with projects2.0, so you'll get into it pretty quick I guess.
Because we just cleaning up - not creating from scratch :)

>

**Comment by atherdon** [comment]
was it finished, right?

**Comment by EbrahimKreem** [comment]
probably yes

**Comment by EbrahimKreem** [comment]
should I close it?

**Comment by atherdon** [comment]
yep

>
