### ISSUE TITLE
remove lines from index.js

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#209]
**Is your feature request related to a problem? Please describe.**
@sibasish14 please remove that part, but check if we're using it at other places or not
https://github.com/GroceriStar/food-datasets-csv-parser/blob/master/src/index.js#L10

**Comment by sibasish14** [comment]
No files in `/src` look like they are using `parseDirectoryFiles`. I also checked other folders but didn't find any file(s) using it. So I think we can remove that line as well as it's export?

**Comment by atherdon** [comment]
sure - do it!

**Comment by atherdon** [comment]
btw, feel free to oepn PRs if you havequestions and show that change - i mean it's more quick for communication

**Comment by atherdon** [comment]
looks completed for me. do you have other tasks to do, right?

**Comment by sibasish14** [comment]
@atherdon I would like some more issues to work on.
