### ISSUE TITLE
About the location of `mainWrapper.js` file

### ISSUE THREAD

**Issue by EbrahimKreem** [GroceriStar/food-datasets-csv-parser#218]
**Is your feature request related to a problem? Please describe.**
I think `mainWrapper.js` file should be in projects2.0 folder.
 it doesn't make sense to let it be in the `src` folder because it's not a part of the core functionality

**Comment by atherdon** [comment]
not sure actually. I mean - our main goal is have less code at our parses.
and as we using the method for each of dataset - i think it's cool to
automate it and keep as part of module - and avoid further duplicates

>
