### ISSUE TITLE
update package.json scripts

### ISSUE THREAD

**Issue by EbrahimKreem** [GroceriStar/food-datasets-csv-parser#227]
**Describe the bug**
with the latest repo structure changes, we have problems in running package.json scripts

**Comment by atherdon** [comment]
sure, definately can be
@sibasish14 maybe can take a look on that

**Comment by atherdon** [comment]
@EbrahimKreem can you explain what exactly is not working cool? path to dist folder at parsers?

**Comment by EbrahimKreem** [comment]
1- path to dist folder
2- invalid location for CSV files inside package.json scripts

**Comment by EbrahimKreem** [comment]
1- path to dist folder
2- invalid location for CSV files inside package.json scripts

**Comment by atherdon** [comment]
you see - this is an actually good case why we should migrate into
projects3.0 version :)

**Comment by sibasish14** [comment]
@EbrahimKreem 
I don't find any `dist` folder. Do you mean the `src` folder?
> 2- invalid path for CSV files inside package.json scripts

Do you mean to provide the right path for the `index.js` file? Something like changing it to- `"main": "package/src/index.cjs.js",`

**Comment by EbrahimKreem** [comment]
> I don't find any dist folder. Do you mean the src folder?

if you look at `projects2.0` parsers the import for `mainWrapper` fn is:
https://github.com/GroceriStar/food-datasets-csv-parser/blob/1c0cf846ecf5414421da1f0b8958200505c46aca/projects2.0/FAO/Fish/Fish_NV_Sum/parser.js#L2 
it is referencing the `dist` folder in the root dir but now with our directory structure changes the `dist` folder will be inside the `package` folder it will not work as expected.

**Comment by EbrahimKreem** [comment]
> Do you mean to provide the right path for the index.js file? Something like changing it to- "main": "package/src/index.cjs.js",

if you look at `package.json` scripts that are inside `package` ex:
https://github.com/GroceriStar/food-datasets-csv-parser/blob/1c0cf846ecf5414421da1f0b8958200505c46aca/package/package.json#L24
the path is invalid because before the `package.json` file was in the root dir now it is inside the `package` dir so we will have to update CSV files path to make it work as expected.

**Comment by sibasish14** [comment]
So I need to update the path in each parser inside `projects 2.0` as `require('../../../package/dist/index.cjs');` Please correct me if I am wrong.

And how should I update the csv files? I am not quite sure about this part.

**Comment by atherdon** [comment]
i think yes - please update those paths

**Comment by EbrahimKreem** [comment]
> And how should I update the csv files? I am not quite sure about this part.

add a dot (.) in the beginning of the path and it will work ex:
`"csv:res": "node ../projects2.0/Restaurants/parser",`

**Comment by sibasish14** [comment]
Any more tasks for me?
