### ISSUE TITLE
move methods that we have in cccsvparser into index.js

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#33]
- i think it will help us to move forward with this module
- we'll be able to remove file with ugly name
- will have a single point of exporting methods to the outside
- will break csv parsers at "projects/USFA/..." folders

#13

**Comment by AndrewSerra** [comment]
Working on it.

**Comment by AndrewSerra** [comment]
I did not remove cccsvparser yet. I have a suggestion. All functions are connected to each other in cccsvparser and only one function is exported, I was thinking of just changing the name of the file and importing the single function that is important in cccsvparser to index.js

**Comment by AndrewSerra** [comment]
Shortly:
1. Changing the name of cccsvparser.js to something useful. (I would name it the same as the function exported from the file which is `csvToJson()`
2. import `csvToJson()` to index.js 
3. export whichever function we want

**Comment by atherdon** [comment]
i make that ugly name - because we have a module inside at pkg.json that was making conflicts. this is why it was changed.

2) you can check at "proejcts" what functions they using and get an idea what should be exported. because this module will be installed to "projects" in future

**Comment by atherdon** [comment]
ok, show me the code

**Comment by AndrewSerra** [comment]
At the moment I have this in index.js:
```
import { parseFoodComposition } from './FoodComposition/csv_parser';

// @TODO soon we should move data from csvParser into index.js
// should we export methods below as well
// fileWriter
// splitJsonIntoFiles
// csvToJson
// parseDirectoryFiles

// @TODO i don't like this name, because if we use it outside - it's very long
import { parseDirectoryFiles } from './fileSystem'; // @TODO i use this name, because rollup was confused. later we'll change it
import { csvToJson } from './CCCSVParser';

export {
  csvToJson,
  parseFoodComposition,
  parseDirectoryFiles,
}
```
and cccsvparser is the same. I am checking what you said now.

**Comment by AndrewSerra** [comment]
I opened a pull request to show what I did. As far as I can see, I only saw the function `parseDirectoryFiles()` that was used in "projects".

**Comment by atherdon** [comment]
Ok,
merged.

check this files
- https://github.com/GroceriStar/food-datasets-csv-parser/blob/master/src/USFA/Serving_Size/parser.js
- https://github.com/GroceriStar/food-datasets-csv-parser/blob/master/src/USFA/Derivation_Code_Description/parser.js
- https://github.com/GroceriStar/food-datasets-csv-parser/blob/master/src/USFA/Nutrition/parser.js
- https://github.com/GroceriStar/food-datasets-csv-parser/blob/master/src/USFA/Product/parser.js

**Comment by AndrewSerra** [comment]
I looked through them while working on another issue, by check do you mean to convert to ES6 style? or check those files and remove unnecessary ones for export?

**Comment by atherdon** [comment]
by check i mean that they all now broken(i assume)

**Comment by AndrewSerra** [comment]
Ok checking it

**Comment by atherdon** [comment]
did we solve all the points from the task description?

**Comment by atherdon** [comment]
ohh, i forget this comments https://github.com/GroceriStar/food-datasets-csv-parser/pull/37#pullrequestreview-262962272
