### ISSUE TITLE
replacing methods from WriteFile.js to methods from generator module

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/food-datasets-csv-parser#56]
**Is your feature request related to a problem? Please describe.**

what do you think about this:
- let's start replacing methods, that we're using from writeFile.js by same methods, that we have at generator module(i.e. `write`, `save`), etc.

i want to do it carefully, but maybe with our current changes at parsers, we will break our code and we don't need to worry about doing it slowly...

**Is it was created as task at GitHub issues? Please provide an issue number or link**
#13 

**Describe the solution you'd like**
My goal is to remove duplicated methods that we can grab from generator. 
So our code will have less weight and will be unified a bit

**Comment by atherdon** [comment]
for example, how i see this transition:
 - writeFile - https://github.com/GroceriStar/food-datasets-csv-parser/blob/master/src/writeFile.js#L36
we comparing this method with https://github.com/GroceriStar/food-static-files-generator/blob/master/src/fileSystem.js#L11

we see small changes, replacing this method at our files that use `writeFile`
and we also removing an sub-method, that `writeFile` using

tell me if something not clear

**Comment by atherdon** [comment]
i don't see errors now, but maybe when we'll start to replace our methods. we'll face some.
Adding here @svr8 because he is actually working with those methods from the generator and can be useful here.

guys, please decide together what to do here

**Comment by AndrewSerra** [comment]
So we are getting rid of functions that we can import from the generator?

**Comment by atherdon** [comment]
yeah, briefly. but we doing it slowlvy and step by step.

let's start with replacing method `writefile` to `write` from generator at all places where it used

**Comment by AndrewSerra** [comment]
Okay starting this task. I'll also convert to ES6

**Comment by AndrewSerra** [comment]
Also, are we adding callbacks?

**Comment by svr8** [comment]
I updated the functions today. Callbacks won't be needed, instead, `write` returns a promise.

**Comment by svr8** [comment]
> So we are getting rid of functions that we can import from the generator?

Okay. Should I start by replacing `readData`?

**Comment by AndrewSerra** [comment]
So I guess it's just copying and pasting from food-static-files-generator to food-dataset-csv-parser? and then modifying wherever else it occurs?

**Comment by AndrewSerra** [comment]
Opened PR for it

**Comment by svr8** [comment]
Yeah. Um also, I am a little confused here..
> So we are getting rid of functions that we can import from the generator?

and
> So I guess it's just copying and pasting from food-static-files-generator to food-dataset-csv-parser? and then modifying wherever else it occurs?

Are we importing methods from the generator or we copy-paste entire code that we need?

**Comment by AndrewSerra** [comment]
> Are we importing methods from the generator or we copy-paste entire code that we need?

yeah that was what I was confused about. So I used your changes and added them to this repo. If it is importing I will change it

**Comment by svr8** [comment]
@atherdon Should we have a common utility api called util that contains small modules that are used in multiple repositories? It would be helpful if there's a need to change the file-structure of data in the future, we'll just need to change the methods in util.

**Comment by atherdon** [comment]
its not copy-pasting.
we exported method write at our generator module.
this module installed at csv-parser - check package.json
we're replacing methods, that was stored here, in `src` folder, to methods,
that was exported at generator module.

tell me if something is not clear

https://github.com/GroceriStar/food-datasets-csv-parser/pull/66#pullrequestreview-264407446


>

**Comment by AndrewSerra** [comment]
okay I'll fix it now

**Comment by atherdon** [comment]
what our next method should be?

**Comment by AndrewSerra** [comment]
there is one file left in ES5. `getHeaders.js`

**Comment by atherdon** [comment]
gotcha. While I don't want to interup the process - let's create a copy of
that file and convert it into es6. when all parser - related work will be
finished  - we'll just replace files and all will be good to go

>

**Comment by atherdon** [comment]
@AndrewSerra I install the lastest version of our generator module, you can continue this task

**Comment by AndrewSerra** [comment]
Okay, I'll create a copy and convert to es6
